# Generated by Django 4.1.4 on 2022-12-31 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homeworks_types", "0001_initial"),
        ("groups", "0002_initial"),
        ("homeworks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homework",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="creator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="homeworks",
                to="groups.bunch",
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="type",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="homework_type",
                to="homeworks_types.homeworktype",
            ),
        ),
    ]
