# Generated by Django 4.1.4 on 2023-01-02 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks_types", "0001_initial"),
        ("homeworks", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="homework",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="homework_type",
                to="homeworks_types.homeworktype",
            ),
        ),
    ]
