# Generated by Django 4.1.4 on 2023-01-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0003_alter_homework_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="homework",
            name="type",
        ),
    ]
