# Generated by Django 4.1.4 on 2023-01-03 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks", "0004_remove_homework_type"),
        ("homeworks_types", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="HomeworkType",
        ),
    ]
