# Generated by Django 4.1.4 on 2022-12-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks_types", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="homeworktype",
            options={
                "ordering": ("title",),
                "verbose_name": "Homework type",
                "verbose_name_plural": "Homework types",
            },
        ),
    ]
