# Generated by Django 4.1.4 on 2022-12-19 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a1964949-3ad2-4a9d-8ca6-09378eb6080c'), primary_key=True, serialize=False, unique=True),
        ),
    ]
