# Generated by Django 4.1.4 on 2022-12-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_remove_review_some_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.FloatField(verbose_name='stars count'),
        ),
    ]
