# Generated by Django 4.1.4 on 2022-12-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0003_rename_duration_bunch_direction"),
        ("directions", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Course",
            new_name="Direction",
        ),
    ]
