# Generated by Django 4.1.4 on 2022-12-19 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Our project', 'verbose_name_plural': 'Our projects'},
        ),
    ]
