# Generated by Django 4.1.4 on 2022-12-19 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('our_projects', '0002_alter_project_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9a92b3e5-82e5-4f64-98c1-db51ea39d360'), primary_key=True, serialize=False, unique=True),
        ),
    ]
