# Generated by Django 4.1.4 on 2022-12-19 06:45

from django.db import migrations, models
import parler.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OurMission',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('8d868386-2b85-4db4-b755-afd5377fe00c'), primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('content', models.TextField(verbose_name='Our Mission')),
            ],
            options={
                'verbose_name': 'Our Mission',
                'verbose_name_plural': 'Our Mission',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
