# Generated by Django 4.1.4 on 2022-12-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeworks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='answer_url')),
            ],
            options={
                'verbose_name': 'Homework Answers Url',
                'verbose_name_plural': 'Homework Answers Urls',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='homeworks.homework')),
            ],
            options={
                'verbose_name': 'Homework Answers',
                'verbose_name_plural': 'Homework Answers',
            },
        ),
    ]
