# Generated by Django 4.1.4 on 2022-12-31 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homeworks_answers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="intern",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="intern",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="url",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="urls",
                to="homeworks_answers.answerurl",
            ),
        ),
    ]
