# Generated by Django 4.1.4 on 2022-12-31 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "admin"),
                            (2, "trainer"),
                            (3, "mentor"),
                            (4, "intern"),
                            (5, "guest"),
                        ],
                        primary_key=True,
                        serialize=False,
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "ordering": ("id",),
            },
        ),
    ]
