# Generated by Django 4.1.4 on 2022-12-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('title', models.CharField(max_length=256, verbose_name="company's title")),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name="company's title")),
                ('ordering', models.PositiveSmallIntegerField(verbose_name='ordering')),
                ('image', models.FileField(upload_to='', verbose_name='logo')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ('ordering',),
            },
        ),
    ]
