# Generated by Django 4.1.4 on 2022-12-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ('ordering',), 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
    ]
