# Generated by Django 4.1.4 on 2022-12-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('image', models.FileField(upload_to='', verbose_name="project's logo")),
                ('title', models.CharField(max_length=256, verbose_name="project's title")),
                ('title_ru', models.CharField(max_length=256, null=True, verbose_name="project's title")),
            ],
            options={
                'verbose_name': 'Our project',
                'verbose_name_plural': 'Our projects',
            },
        ),
    ]
