# Generated by Django 4.1.4 on 2022-12-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roles", "0001_initial"),
        ("users", "0004_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.ManyToManyField(to="roles.role"),
        ),
    ]
