# Generated by Django 4.1.4 on 2022-12-19 07:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6460b128-f4c7-44ac-ba2b-575fc1694027'), primary_key=True, serialize=False, unique=True),
        ),
    ]
