# Generated by Django 4.1.4 on 2022-12-19 17:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('18a162a7-853f-4f3e-97ac-1cf3d04ddbe9'), primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('first_name', models.CharField(max_length=256, verbose_name='first name')),
                ('last_name', models.CharField(max_length=256, verbose_name='last name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('image', models.ImageField(upload_to='', verbose_name='image')),
                ('position', models.CharField(choices=[('Front-end Developer', 'Front End'), ('Back-end Developer', 'Back End'), ('Designer', 'Designer'), ('Android Developer', 'Android'), ('Ios Developer', 'Ios')], max_length=256, verbose_name='position')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
                'ordering': ('created_at',),
            },
        ),
    ]
