# Generated by Django 4.1.4 on 2022-12-30 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата последнего изменения')),
                ('first_name', models.CharField(max_length=256, verbose_name='first name')),
                ('first_name_ru', models.CharField(max_length=256, null=True, verbose_name='first name')),
                ('last_name', models.CharField(max_length=256, verbose_name='last name')),
                ('last_name_ru', models.CharField(max_length=256, null=True, verbose_name='last name')),
                ('age', models.PositiveSmallIntegerField(verbose_name='age')),
                ('age_ru', models.PositiveSmallIntegerField(null=True, verbose_name='age')),
                ('image', models.ImageField(upload_to='team/images/', verbose_name='image')),
                ('position', models.CharField(choices=[('Front-end Developer', 'Front End'), ('Back-end Developer', 'Back End'), ('Designer', 'Designer'), ('Android Developer', 'Android'), ('Ios Developer', 'Ios'), ('Tech Lead', 'Tech Lead'), ('CEO', 'Ceo'), ('PM', 'Pm')], max_length=256, verbose_name='position')),
                ('position_ru', models.CharField(choices=[('Front-end Developer', 'Front End'), ('Back-end Developer', 'Back End'), ('Designer', 'Designer'), ('Android Developer', 'Android'), ('Ios Developer', 'Ios'), ('Tech Lead', 'Tech Lead'), ('CEO', 'Ceo'), ('PM', 'Pm')], max_length=256, null=True, verbose_name='position')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
                'ordering': ('created_at',),
            },
        ),
    ]
