# Generated by Django 4.1.4 on 2022-12-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("our_team", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="image",
            field=models.ImageField(upload_to="team/images/", verbose_name="image"),
        ),
    ]
