# Generated by Django 4.1.4 on 2022-12-30 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homeworks_answers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homeworks_answers.answer')),
            ],
            options={
                'verbose_name': 'Answer Comments',
                'verbose_name_plural': 'Answers Comments',
                'ordering': ('-created_at',),
            },
        ),
    ]
