# Generated by Django 4.1.4 on 2022-12-29 10:22

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks_answers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("homeworks_answers_comments", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comments",
            new_name="Comment",
        ),
    ]
