# Generated by Django 4.1.4 on 2023-01-02 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeworks_answers", "0004_alter_answerurl_answer"),
        ("homeworks_answers_comments", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="homeworks_answers.answer",
            ),
        ),
    ]
