# Generated by Django 4.1.4 on 2022-12-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="achievement",
            name="files",
        ),
        migrations.AddField(
            model_name="achievement",
            name="file",
            field=models.ImageField(
                default=1, upload_to="images/achievements/", verbose_name="file"
            ),
            preserve_default=False,
        ),
    ]
