# Generated by Django 4.1.4 on 2023-01-11 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0002_alter_bunch_members"),
    ]

    operations = [
        migrations.AddField(
            model_name="bunch",
            name="mentors",
            field=models.ManyToManyField(
                related_name="mentors", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
