# Generated by Django 4.1.4 on 2022-12-30 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("groups", "0003_rename_duration_bunch_direction"),
    ]

    operations = [
        migrations.AddField(
            model_name="bunch",
            name="members",
            field=models.ManyToManyField(
                related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
